# Generated by Django 4.2.3 on 2025-05-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_yummy1', '0002_item_endereco_item_latitude_item_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço relacionado à lista', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lista',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude da localização da lista', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lista',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude da localização da lista', max_digits=9, null=True),
        ),
    ]
